### ISSUE TITLE
Install-Svn.ps1 is failing 

### ISSUE THREAD

**Issue by lokesh755** [Microsoft/vsts-image-generation#107]
Chocolatey install of SVN is not working. It seems URL used by chocolatey is not longer working.

**Comment by DavidStaheli** [comment]
@lokesh755 It looks like SourceForge was temporarily down.  The URL is working again and I tested that `choco install svn -y` works.

https://sourceforge.net/projects/win32svn/files/1.8.15/Setup-Subversion-1.8.15.msi

**Comment by gep13** [comment]
@lokesh755 @DavidStaheli depending on your setup (since 3rd party downloads can, and do, go away) you might want to look at internalising the packages that you are reliant on, so that your image generations will always work.  The process is documented here:

https://chocolatey.org/docs/how-to-recompile-packages

**Comment by DavidStaheli** [comment]
Nice!  Thanks @gep13.
