### ISSUE TITLE
Run-Antivirus.ps1 sometimes results in 0x800106ba Windows Defender error

### ISSUE THREAD

**Issue by ryanspletzer** [Microsoft/vsts-image-generation#159]
This seems non-deterministic and will work sometimes, but is hard to test because it's at the very end of the build... which can take about 4 hours. If I move it to the front end of the build this step tends to work just fine.

When it gets to the [MsMpCmd.exe](https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Run-Antivirus.ps1#L11) step it may fail with:

```
CmdTool: Failed with hr = 0x800106BA. Check C:\Users\ADMINI~1\AppData\Local\Temp\MpCmdRun.log for more information
```

And after that fails [Set-MsMpPreference](https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/scripts/Installers/Vs2017/Run-Antivirus.ps1#L15) also fails with:

```
+ Set-MpPreference -ScanAvgCPULoadFactor 5 `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [SetMpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Set-MpPreference
```

This is right after the machine comes back up from a reboot....

I'm hypothesizing if building in a pause step to allow the Windows Defender service to get "warmed up" after the reboot may help?

Have you guys ever seen this before when you run it?

**Comment by lokesh755** [comment]
I've generated images with current repo many times, but I've never seen this issue. Did you change any builder settings ? How often you see this problem ? If it's too often can you add packer param "[-on-error=abort](https://www.packer.io/docs/commands/build.html)" , which will avoid packer to delete VM in case of any error . So that you can debug more easily and also collect logs.

**Comment by lokesh755** [comment]
Are you able to collect the logs ?

**Comment by ryanspletzer** [comment]
I just let it run again and it got to the antivirus scan part and made it in successfully this time with the code as-is and is in the process of scanning. Not sure what caused that to happen a few times... it may be non-deterministic and hard to reproduce, so we can probably close this out.

By the way, how long does the Run-Antivirus.ps1 step typically take for you guys? I see it take about 8 hours for me.

**Comment by ryanspletzer** [comment]
I ran it again and it did hit the error this time, but I wasn't expecting it and didn't have the on-error=abort or on-error=ask flags... To be totally transparent we are using an AMI builder on AWS with all the same scripts and I'm not sure if that's just enough of a change in environment to cause this to happen, but in any case it's probably outside the scope of worrying about it here and we can close the issue.

For any other person that may see this down the road, my googling tells me that this happens when the Windows Defender service is stopped and/or not fully warmed up. We've tested in some cases with another provisioned step that runs before Run-Antivirus.ps1 called Start-AntivirusService.ps1 which ensures the Windows Defender service is started after the reboot and also pauses (start-sleep) for 90 seconds to give it enough time to warm up.

**Comment by lokesh755** [comment]
Probably, it's due to the base image used on AWS. I'm not really sure, since I've not tried on AWS.

**Comment by NateB2** [comment]
Just FYI, I've been working on generating Server 2019 images in Azure using the VS 2017 build script, and I received this error about 95% of the time.  After a ton of troubleshooting, I found that running "Update-MpSignature" immediately before running the scan appears to fix the issue.  I made the change, and now the Server 2019 image generates reliably.

However, that step fails in Server 2016.  Because we have developers that require Server 2016 Docker containers, and thus we need to generate images for both operating systems, I added a conditional which appears to fix the issue for both:

`
if ($psversiontable.psversion.build -ge 17763) {
    Update-MpSignature
}
`

I bring this up because hopefully it will help when the Azure DevOps team starts building Server 2019 images.  I didn't submit a PR because the current script is working fine for Server 2016, but I can if you guys want.
