### ISSUE TITLE
Problem with Hosted Pool Linux (Preview) image - has SSL 1.1 now instead of SSL 1.0.0

### ISSUE THREAD

**Issue by mahilleb-msft** [Microsoft/vsts-image-generation#161]
Since last Friday, the Linux Hosted Pool Image (preview) in VSTS pulls in lib SSL in version 1.1 (instead of Ubuntu 16.04 default lib SSL 1.0.0). Version 1.1 gets picked up in a build of ours, thus creating a binary that's not compatible anymore with vanilla Ubuntu 16.04. (It used to work fine in older versions of the image).

Note: It seems that SSL 1.1 is coming from the PHP install.
When building

```
https://github.com/Microsoft/vsts-agent-docker/blob/master/ubuntu/16.04/standard/Dockerfile
```

we see:

```
Step 37/49 : RUN apt-add-repository ppa:ondrej/php -y  && apt-get update  && apt-get install -y --no-install-recommends     php5.6     php7.0     php7.1     php7.1-amqp     php-apcu     php7.1-bcmath     php7.1-
bz2     php7.1-curl     php7.1-dev     php7.1-fpm     php7.1-gd     php7.1-intl     php7.1-json     php7.1-mbstring     php7.1-mcrypt     php7.1-mysql     php7.1-pgsql     php7.1-sqlite     php7.1-xml     php7.1
-zip     php7.2     php-igbinary     php-memcache     php-memcached     php-mongodb     php-redis     php-xdebug     php-yaml     php-zmq  && apt-get remove --purge -yq php7.1-dev  && rm -rf /var/lib/apt/lists/*
 ---> Running in eb7218f951f5
...
Get:17 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libssl1.1 amd64 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 [1,341 kB]
```

Note: @bryanmacfarlane advised to create this issue here, rather than in Microsoft/vsts-agent-docker.

**Comment by dakale** [comment]
In general because we provision images from package repos and pick up latest versions, it is not up to us whether new packages versions break backwards compatibility. `libssl1.0.0` and `libssl1.1` are separate independently versioned packages providing different levels of api compatibility. I believe in particular these packages can both be installed without issue, in fact this is how we provide multiple levels of compatibility for things like dotnet and php as you showed. For your build, you may need to specifically link or compile against libssl1.0.0 which will still exist on the image

libssl.so.1.1 is found at /usr/lib/x86_64-linux-gnu 
libssl.so.1.0.0 is found at /lib/x86_64-linux-gnu
per:
```bash
root@953da2c9c33a:/vsts# ls /usr/lib/x86_64-linux-gnu/ | grep ssl
libgnutls-openssl.so.27
libgnutls-openssl.so.27.0.2
libssl3.so
libssl.a
libssl.so
libssl.so.1.1
openssl-1.0.0
root@953da2c9c33a:/vsts# ls /lib/x86_64-linux-gnu/ | grep ssl
libssl.so.1.0.0
```

If thats not an option you can modify the image in your build in anyway you see fit, eg in an early phase uninstall the 1.1 package so that your build picks up the version you, but that has obvious downsides. Let me know if none of these options work for you

**Comment by mahilleb-msft** [comment]
Yes, both libraries are present. For now, we're working the problem by downgrading libssl-dev (which for some reason is install through the PHP PPA install) to 1.0, which then makes the build go against the standard SSL version. Thanks.

**Comment by lmussier** [comment]
@mahilleb-msft Hi, we are facing the same problem, could you provide an ETA for this issue ?
Thanks.

**Comment by mahilleb-msft** [comment]
Hi @lmussier, as I said, we worked around by removing the libssl 1.1 when our build starts.
You could try also other options that @dakale suggested above.

Thanks, Mark
