### ISSUE TITLE
Change packer script to generate managed images

### ISSUE THREAD

**Issue by NateB2** [Microsoft/vsts-image-generation#81]
As per Microsoft's guidelines, it appears as if they want us to start using managed images for VMs instead of storage accounts.  The Azure builder theoretically supports managed images, so it would be nice if the packer script was changed to support generating managed images as well.  Deploying VMs is easier with managed images, and doesn't require fiddling around with storage accounts.

I've tried to convert the packer script myself, but ran into an issue where it would generate a Windows 2016 managed image that was unusable when deployed to VMs, so this might not be possible until that issue is resolved.  I've filed a bug [here](https://github.com/hashicorp/packer/issues/5945) with an extremely stripped-down script that's based off of the "VS2017-Server2016-Azure" script.

**Comment by lokesh755** [comment]
We had managed builder as part of packer template earlier, but it was removed since it's not beneficial to everyone to generate multiple images. If you want to add managed builder you can copy it from the earlier release template . For reference https://github.com/Microsoft/vsts-image-generation/blob/releases/1712/images/win/Vs2017/vs2017-Server2016-Azure.json#L46
