### ISSUE TITLE
Docker images based on nanoserver-1709 not building on hosted VS2017 agent

### ISSUE THREAD

**Issue by Hammatt** [Microsoft/vsts-image-generation#85]
Docker images based on nanoserver-1709 don't build on hosted agents. See Microsoft/vsts-tasks#6510  
Is there any chance this could get looked into, we're trying to avoid setting up and maintaining our own build-server.

Thanks

**Comment by chrisrpatterson** [comment]
Hi @Hammatt because we provide full VS 2017 in an interactive desktop environment we need to run on full windows server and not server core.  Unfortunately, in the 1709+ versions of Windows are shipped as Server Core only and as such support a much more limited workload.  We do have plans to enable a new image that is running Windows Server with Docker that will use the new server core skus but will be limited to running docker only.  I currenly do not have a final date for that but I expect it to be early summer or late spring.

**Comment by artisticcheese** [comment]
Is it possible to run this agent on Windows 10 machine instead? So you can still build images with 1709, 1803 tags while maintaining all the development software intact?
